# Generated by Django 4.0.5 on 2022-10-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=18, verbose_name='Filial')),
                ('fluigNumber', models.IntegerField(verbose_name='Numero do fluig')),
                ('prefix', models.CharField(max_length=20, verbose_name='Prefixo')),
                ('titleNumber', models.IntegerField(verbose_name='Numero do titulo')),
                ('installment', models.CharField(max_length=10, verbose_name='Parcela')),
                ('type', models.CharField(max_length=18, verbose_name='Tipo')),
                ('dueDate', models.DateField(verbose_name='Vencimento')),
                ('titleValue', models.CharField(max_length=20, verbose_name='Preco do titulo')),
                ('status', models.IntegerField(default=2, verbose_name='Status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='FornecedorTitulo', to='fornecedores.fornecedores', verbose_name='Fornecedor')),
            ],
        ),
    ]
