# Generated by Django 4.0.5 on 2022-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Máximo de 100 caracteres', max_length=100, verbose_name='Descrição')),
                ('codErp', models.CharField(max_length=12, verbose_name='Código ERP')),
            ],
        ),
    ]
