# Generated by Django 4.0.5 on 2022-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='Produto')),
                ('productCode', models.IntegerField()),
                ('defaultSupplier', models.CharField(blank=True, max_length=8, null=True, verbose_name='Fornecedor Padrão')),
                ('item', models.CharField(help_text='Máximo de 3 caracteres', max_length=3)),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('necessityDate', models.DateField(verbose_name='Data de necessidade')),
                ('unit', models.CharField(blank=True, max_length=2, null=True)),
                ('quantity', models.IntegerField()),
                ('currency', models.CharField(max_length=2)),
            ],
        ),
    ]
