# Generated by Django 4.0.5 on 2022-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Máximo de 100 caracteres', max_length=100, verbose_name='Nome')),
                ('description', models.CharField(help_text='Máximo de 100 caracteres', max_length=100, verbose_name='Descrição')),
                ('unit', models.CharField(max_length=3, verbose_name='Unidade de medida')),
                ('codErp', models.CharField(max_length=12, verbose_name='Código ERP')),
                ('defaultSupplier', models.CharField(blank=True, max_length=8, null=True, verbose_name='Fornecedor Padrão')),
            ],
        ),
    ]
