# Generated by Django 4.0.5 on 2022-10-07 18:29

from django.db import migrations, models
import solicitacaoCompras.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=18)),
                ('socialName', models.CharField(blank=True, max_length=40, verbose_name='Razão')),
                ('fantasyName', models.CharField(max_length=20, verbose_name='Fantasia')),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('address', models.CharField(blank=True, help_text='Máximo de 100 caracteres', max_length=100, verbose_name='Endereço')),
                ('district', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('DDD', models.CharField(default='', max_length=3)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('mobilePhone', models.CharField(blank=True, default='', max_length=15)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('erp', models.CharField(blank=True, max_length=12, verbose_name='Código ERP')),
                ('approve', models.IntegerField(default=3)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('cartaoCNPJ', models.FileField(blank=True, null=True, upload_to='anexos', validators=[solicitacaoCompras.validators.validate_file_extension])),
                ('cadastroSintegra', models.FileField(blank=True, null=True, upload_to='anexos', validators=[solicitacaoCompras.validators.validate_file_extension])),
                ('certidaoNegativaRF', models.FileField(blank=True, null=True, upload_to='anexos', validators=[solicitacaoCompras.validators.validate_file_extension])),
                ('contratoSocial', models.FileField(blank=True, null=True, upload_to='anexos', validators=[solicitacaoCompras.validators.validate_file_extension])),
                ('certidaoNegativaFGTS', models.FileField(blank=True, null=True, upload_to='anexos', validators=[solicitacaoCompras.validators.validate_file_extension])),
                ('certidaoNegativaTrabalhista', models.FileField(blank=True, null=True, upload_to='anexos', validators=[solicitacaoCompras.validators.validate_file_extension])),
                ('outrosAnexos', models.FileField(blank=True, null=True, upload_to='anexos', validators=[solicitacaoCompras.validators.validate_file_extension])),
                ('dadosBanco', models.FileField(blank=True, null=True, upload_to='banco', validators=[solicitacaoCompras.validators.validate_file_extension])),
            ],
        ),
    ]
