# Generated by Django 4.0.5 on 2022-10-07 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itensSolicitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCompra',
            fields=[
                ('solicitacaoId', models.AutoField(primary_key=True, serialize=False)),
                ('fluigNumber', models.IntegerField(blank=True, null=True)),
                ('expenseTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(help_text='Máximo de 4 caracteres', max_length=4)),
                ('issueDate', models.DateField(auto_now=True, verbose_name='Emissão')),
                ('alreadyListed', models.IntegerField(default=1)),
                ('itens', models.ManyToManyField(related_name='solicitacao', to='itensSolicitacao.solicitacaoitem')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
